Repository Morph1s/Psychopompos, pull requests merged in 2025-07, with the labels that each got.

#232 feat: updated card rewards for medianight release version
  scripts/global/deck_handler.gd
  scripts/rewards/battle_reward_button.gd
  scripts/rewards/battle_rewards.gd
Labels: refactoring

#235 feat: protagonist sprite
  assets/graphics/characters/placeHolder_player1.png
  assets/graphics/characters/protagonist_v1.png
  assets/graphics/characters/protagonist_v1.png.import
  scenes/characters/character.tscn
Labels: pixelart sprint 1

#238 fix: dulicating shader material for enemies
  resources/shaders/hit_frame_shader.gdshader
  scripts/enemy/enemy.gd
Labels: bug

#242 feat: encounter loading
  resources/encounters/battle_stage_0.tres
  resources/encounters/battle_stage_1_1.tres
  resources/encounters/battle_stage_1_2.tres
  resources/encounters/battle_stage_1_3.tres
  resources/encounters/battle_stage_2_1.tres
  resources/encounters/battle_stage_2_2.tres
  resources/encounters/battle_stage_2_3.tres
  resources/encounters/boss_battle_medusa.tres
  resources/encounters/mini_boss_battle_minotaur.tres
  resources/enemies/chimera.tres
  resources/enemies/gorgone.tres
  resources/enemies/medusa.tres
  resources/enemies/minotaur.tres
  resources/enemies/orthos.tres
  resources/enemies/siren.tres
  scripts/battle/battle.gd
  scripts/custom_resources/map/battle_encounter.gd
  scripts/custom_resources/map/boss_encounter.gd
  scripts/custom_resources/map/mini_boss_encounter.gd
  scripts/map/map.gd
  scripts/run/encounter_handler.gd
  scripts/run/run.gd
  scripts/ui/ui_layer.gd
Labels: important

#237 feat: relocate hud pictograms
  scenes/ui/run_ui.tscn
Labels: refactoring

#245 feat: relic pictograms
  assets/graphics/relics/relic_ambrosia.png
  assets/graphics/relics/relic_ambrosia.png.import
  assets/graphics/relics/relic_bottle_of_ichor.png
  assets/graphics/relics/relic_bottle_of_ichor.png.import
  assets/graphics/relics/relic_eye_of_graeae.png
  assets/graphics/relics/relic_eye_of_graeae.png.import
  assets/graphics/relics/relic_hermes_winged_boots.png
  assets/graphics/relics/relic_hermes_winged_boots.png.import
  assets/graphics/relics/relic_nectar.png
  assets/graphics/relics/relic_nectar.png.import
  assets/graphics/relics/relic_twig_of_lethe.png
  assets/graphics/relics/relic_twig_of_lethe.png.import
  resources/artifacts/ambrosia.tres
  resources/artifacts/bottle_of_icor.tres
  resources/artifacts/eye_of_graeae.tres
  resources/artifacts/hermes_winged_boots.tres
  resources/artifacts/nectar.tres
  resources/artifacts/twig_of_lethe.tres
Labels: pixelart sprint 2

#247 feat: parry card
  assets/graphics/cards/common/card_common_parry.png
  assets/graphics/cards/common/card_common_parry.png.import
  resources/cards/warrior/common/parry.tres
  resources/characters/warrior_cards.tres
Labels: resource, pixelart sprint 2

#246 feat: Enemy Sprites
  assets/graphics/enemies/boss_medusa.png
  assets/graphics/enemies/boss_medusa.png.import
  assets/graphics/enemies/enemy_chimera.png
  assets/graphics/enemies/enemy_chimera.png.import
  assets/graphics/enemies/enemy_gorgone.png
  assets/graphics/enemies/enemy_gorgone.png.import
  assets/graphics/enemies/enemy_orthos.png
  assets/graphics/enemies/enemy_orthos.png.import
  assets/graphics/enemies/enemy_sirene.png
  assets/graphics/enemies/enemy_sirene.png.import
  assets/graphics/enemies/mini_boss_minotaur.png
  assets/graphics/enemies/mini_boss_minotaur.png.import
  resources/enemies/chimera.tres
  resources/enemies/gorgone.tres
  resources/enemies/medusa.tres
  resources/enemies/minotaur.tres
  resources/enemies/orthos.tres
  resources/enemies/siren.tres
Labels: pixelart sprint 1, pixelart sprint 2

#252 refactor: changed calculation for enemy position
  scripts/battle/enemy_handler.gd
Labels: refactoring

#261 refactor: remove battle difficulty
  resources/encounters/battle_stage_1_1.tres
  resources/encounters/battle_stage_1_2.tres
  resources/encounters/battle_stage_1_3.tres
  resources/encounters/battle_stage_2_1.tres
  resources/encounters/battle_stage_2_2.tres
  resources/encounters/battle_stage_2_3.tres
Labels: refactoring

#259 fix: stats now reset after run
  resources/characters/Warrior_Stats.tres
  resources/enemies/chimera.tres
  resources/enemies/gorgone.tres
  resources/enemies/medusa.tres
  resources/enemies/minotaur.tres
  resources/enemies/orthos.tres
  resources/enemies/siren.tres
  scripts/custom_resources/entity_stats.gd
  scripts/custom_resources/player_stats.gd
  scripts/run/run.gd
Labels: bug, refactoring

#264 fix: card playing without target fix
  scripts/battle/enemy_handler.gd
Labels: bug

#266 refector: swaped description sprites for helenos
  resources/cards/warrior/hero/helenos.tres
Labels: refactoring

#270 feat: tooltips with values
  resources/artifacts/hermes_winged_boots.tres
  resources/artifacts/twig_of_lethe.tres
  resources/cards/warrior/common/prepare.tres
  resources/cards/warrior/common/respite.tres
  resources/cards/warrior/common/scrape.tres
  resources/cards/warrior/common/swipe.tres
  resources/cards/warrior/gods_boon/eris.tres
  resources/cards/warrior/gods_boon/hades.tres
  resources/cards/warrior/gods_boon/ker.tres
  resources/cards/warrior/gods_boon/nemesis.tres
  resources/cards/warrior/gods_boon/thanatos.tres
  resources/cards/warrior/hero/actaeon.tres
  resources/cards/warrior/hero/damokles.tres
  resources/cards/warrior/hero/idas.tres
  resources/cards/warrior/hero/nestor.tres
  resources/cards/warrior/hero/odysseus.tres
  resources/tooltips/action_tooltips/attack_all_tooltip.tres
  resources/tooltips/action_tooltips/attack_tooltip.tres
  resources/tooltips/action_tooltips/block_tooltip.tres
  resources/tooltips/action_tooltips/card_draw_tooltip.tres
  resources/tooltips/action_tooltips/coins_tooltip.tres
  resources/tooltips/action_tooltips/damokles_sword_action_tooltip.tres
  resources/tooltips/action_tooltips/discard_random_tooltip.tres
  resources/tooltips/action_tooltips/gather_action_tooltip.tres
  resources/tooltips/action_tooltips/phalanx_action_tooltip.tres
  resources/tooltips/action_tooltips/regeneration_action_tooltip.tres
  resources/tooltips/action_tooltips/select_card_tooltip.tres
  resources/tooltips/action_tooltips/vigilant_action_tooltip.tres
  resources/tooltips/action_tooltips/warriors_furry_action_tooltip.tres
  resources/tooltips/action_tooltips/wounded_action_tooltip.tres
  resources/tooltips/artifact_tooltips/ambrosia_tooltip.tres
  resources/tooltips/artifact_tooltips/bottle_of_icor_tooltip.tres
  resources/tooltips/artifact_tooltips/eye_of_graeae_tooltip.tres
  resources/tooltips/artifact_tooltips/hermes_winged_boots_tooltip.tres
  resources/tooltips/artifact_tooltips/nectar_tooltip.tres
  resources/tooltips/artifact_tooltips/twig_of_lethe_tooltip.tres
  resources/tooltips/effect_tooltips/agile_tooltip.tres
  resources/tooltips/effect_tooltips/damokles_sword_tooltip.tres
  resources/tooltips/effect_tooltips/gather_tooltip.tres
  resources/tooltips/effect_tooltips/incapacitated_tooltip.tres
  resources/tooltips/effect_tooltips/phalanx_tooltip.tres
  resources/tooltips/effect_tooltips/regeneration_tooltip.tres
  resources/tooltips/effect_tooltips/vigilant_tooltip.tres
  resources/tooltips/effect_tooltips/warriors_furry_tooltip.tres
  resources/tooltips/effect_tooltips/wounded_tooltip.tres
  resources/tooltips/special_tooltips/eris_discard_tooltip.tres
  resources/tooltips/special_tooltips/eris_draw_tooltip.tres
  resources/tooltips/special_tooltips/hermes_winged_boots_agile_tooltip.tres
  resources/tooltips/special_tooltips/thanatos_gather_tooltip.tres
  resources/tooltips/special_tooltips/thanatos_tooltip.tres
  scenes/ui/tooltip.tscn
  scripts/card/card.gd
  scripts/card/card_visualization.gd
  scripts/custom_resources/tooltip_data.gd
  scripts/effects/effect_interface.gd
  scripts/rewards/battle_reward_button.gd
  scripts/ui/run_ui.gd
  scripts/ui/tooltip.gd
Labels: refactoring, script, resource, difficult

#277 feat: added card pile card count labels
  scenes/ui/battle_ui.tscn
  scripts/battle/battle_ui.gd
  scripts/battle/card_handler.gd
  scripts/global/event_bus_handler.gd
Labels: refactoring, scene

#279 feat: check for it being the players turn when giving control back
  scenes/encounters/battle.tscn
  scripts/battle/battle.gd
  scripts/battle/card_handler.gd
  scripts/battle/state_machine/idle.gd
Labels: bug

#280 feat: campfire background texture
  assets/graphics/background/wallpaper_campfire_scene.png
  assets/graphics/background/wallpaper_campfire_scene.png.import
  scenes/encounters/campfire.tscn
Labels: pixelart sprint 2

#278 refactor: Fix and add map sprites
  assets/graphics/map/map_background.png
  assets/graphics/map/map_sprite.png
  assets/graphics/map/map_sprite.png.import
  scenes/map/map.tscn
Labels: refactoring

#282 feat: description text color
  resources/artifacts/bottle_of_icor.tres
  resources/cards/warrior/common/flurry.tres
  resources/cards/warrior/common/guard.tres
  resources/cards/warrior/common/hit.tres
  resources/cards/warrior/common/parry.tres
  resources/cards/warrior/common/poke.tres
  resources/cards/warrior/common/prepare.tres
  resources/cards/warrior/common/respite.tres
  resources/cards/warrior/common/scrape.tres
  resources/cards/warrior/common/swipe.tres
  resources/cards/warrior/gods_boon/eris.tres
  resources/cards/warrior/gods_boon/hades.tres
  resources/cards/warrior/gods_boon/hermes.tres
  resources/cards/warrior/gods_boon/ker.tres
  resources/cards/warrior/gods_boon/nemesis.tres
  resources/cards/warrior/gods_boon/thanatos.tres
  resources/cards/warrior/hero/actaeon.tres
  resources/cards/warrior/hero/damokles.tres
  resources/cards/warrior/hero/hektor.tres
  resources/cards/warrior/hero/helenos.tres
  resources/cards/warrior/hero/idas.tres
  resources/cards/warrior/hero/kassandra.tres
  resources/cards/warrior/hero/nestor.tres
  resources/cards/warrior/hero/odysseus.tres
  resources/enemies/siren.tres
  scenes/ui/enemy_hud.tscn
  scripts/card/card.gd
  scripts/card/card_visualization.gd
  scripts/custom_resources/card_type.gd
  scripts/enemy/enemy.gd
  scripts/ui/enemy_hud.gd
Labels: refactoring

#286 fix: minotaur second attack
  resources/enemies/minotaur.tres
Labels: bug

#311 feat: enemy action timings
  scripts/battle/enemy_handler.gd
  scripts/enemy/enemy.gd
Labels: combat, refactoring

#305 feat: refined tooltips
  resources/cards/warrior/common/flurry.tres
  resources/cards/warrior/gods_boon/hades.tres
  resources/tooltips/action_tooltips/attack_all_tooltip.tres
  resources/tooltips/action_tooltips/attack_tooltip.tres
  resources/tooltips/action_tooltips/block_tooltip.tres
  resources/tooltips/action_tooltips/card_draw_tooltip.tres
  resources/tooltips/action_tooltips/coins_tooltip.tres
  resources/tooltips/action_tooltips/damokles_sword_action_tooltip.tres
  resources/tooltips/action_tooltips/discard_random_tooltip.tres
  resources/tooltips/action_tooltips/gather_action_tooltip.tres
  resources/tooltips/action_tooltips/phalanx_action_tooltip.tres
  resources/tooltips/action_tooltips/regeneration_action_tooltip.tres
  resources/tooltips/action_tooltips/select_card_tooltip.tres
  resources/tooltips/action_tooltips/vigilant_action_tooltip.tres
  resources/tooltips/action_tooltips/warriors_furry_action_tooltip.tres
  resources/tooltips/action_tooltips/wounded_action_tooltip.tres
  resources/tooltips/artifact_tooltips/ambrosia_tooltip.tres
  resources/tooltips/artifact_tooltips/bottle_of_icor_tooltip.tres
  resources/tooltips/artifact_tooltips/eye_of_graeae_tooltip.tres
  resources/tooltips/artifact_tooltips/hermes_winged_boots_tooltip.tres
  resources/tooltips/artifact_tooltips/nectar_tooltip.tres
  resources/tooltips/artifact_tooltips/twig_of_lethe_tooltip.tres
  resources/tooltips/effect_tooltips/agile_tooltip.tres
  resources/tooltips/effect_tooltips/damokles_sword_tooltip.tres
  resources/tooltips/effect_tooltips/gather_tooltip.tres
  resources/tooltips/effect_tooltips/incapacitated_tooltip.tres
  resources/tooltips/effect_tooltips/phalanx_tooltip.tres
  resources/tooltips/effect_tooltips/regeneration_tooltip.tres
  resources/tooltips/effect_tooltips/vigilant_tooltip.tres
  resources/tooltips/effect_tooltips/warriors_furry_tooltip.tres
  resources/tooltips/effect_tooltips/wounded_tooltip.tres
  resources/tooltips/special_tooltips/eris_discard_tooltip.tres
  resources/tooltips/special_tooltips/eris_draw_tooltip.tres
  resources/tooltips/special_tooltips/flurry_tooltip.tres
  resources/tooltips/special_tooltips/hades_tooltip.tres
  resources/tooltips/special_tooltips/hermes_winged_boots_agile_tooltip.tres
  resources/tooltips/special_tooltips/thanatos_gather_tooltip.tres
  resources/tooltips/special_tooltips/thanatos_tooltip.tres
  scripts/custom_resources/tooltip_data.gd
Labels: refactoring

#315 refactor: remove campfire from random encounter
  scripts/run/encounter_handler.gd
Labels: refactoring

#353 refactor: standardized encounter finishing
  scenes/encounters/battle_rewards.tscn
  scripts/encounters/campfire.gd
  scripts/encounters/dialogue.gd
  scripts/encounters/shop.gd
  scripts/global/event_bus_handler.gd
  scripts/rewards/battle_rewards.gd
  scripts/run/encounter_handler.gd
  scripts/run/run.gd
  scripts/ui/ui_layer.gd
Labels: refactoring

#369 fix: battle state machine transition triggers
  scenes/encounters/battle.tscn
  scripts/battle/battle.gd
  scripts/battle/card_handler.gd
  scripts/battle/enemy_handler.gd
  scripts/battle/state_machine/enemy_end_turn.gd
  scripts/battle/state_machine/enemy_start_turn.gd
  scripts/battle/state_machine/enemy_turn.gd
  scripts/battle/state_machine/idle.gd
  scripts/battle/state_machine/player_end_turn.gd
  scripts/battle/state_machine/player_start_turn.gd
  scripts/battle/state_machine/state.gd
  scripts/characters/player.gd
  scripts/effects/effect_handler.gd
  scripts/enemy/enemy.gd
Labels: bug, combat

#347 feat: Card Zeus
  assets/graphics/cards/card_effect_zeus.png
  assets/graphics/cards/card_effect_zeus.png.import
  assets/graphics/cards/god/card_god_zeus.png
  assets/graphics/cards/god/card_god_zeus.png.import
  resources/cards/warrior/gods_boon/zeus.tres
  resources/characters/warrior_cards.tres
  resources/tooltips/special_tooltips/zeus_tooltip.tres
  scripts/card/card.gd
  scripts/custom_resources/special_action.gd
Labels: scene, script

#372 Feature/340 balancing and expensions of dialogue system
  resources/dialogue/Hekates_Choice.tres
  resources/dialogue/persephones_banquet.tres
  resources/dialogue/the_high_priestess.tres
  resources/dialogue/three_sisters.tres
  resources/dialogue/tree_stump.tres
  scripts/encounters/dialogue_response.gd
  scripts/encounters/dialogue_ui.gd
  scripts/run/encounter_handler.gd
Labels: script, resource, dialogue

#373 feat: added enemy intent tooltips
  resources/enemies/chimera.tres
  resources/enemies/gorgone.tres
  resources/enemies/medusa.tres
  resources/enemies/minotaur.tres
  resources/enemies/orthos.tres
  resources/enemies/siren.tres
  resources/enemies/test_enemy.tres
  resources/tooltips/enemy_tooltips/enemy_attack_tooltip.tres
  resources/tooltips/enemy_tooltips/enemy_buff_tooltip.tres
  resources/tooltips/enemy_tooltips/enemy_debuff_tooltip.tres
  resources/tooltips/enemy_tooltips/enemy_defend_tooltip.tres
  resources/tooltips/enemy_tooltips/enemy_questionmark_action_tooltip.tres
  scenes/enemy/enemy.tscn
  scenes/ui/enemy_hud.tscn
  scripts/custom_resources/enemy_action.gd
  scripts/custom_resources/enemy_stats.gd
  scripts/enemy/enemy.gd
  scripts/ui/enemy_hud.gd
Labels: combat

#383 feat: added new cards to card rewards, set a value for zeus
  resources/cards/warrior/common/prepare.tres
  resources/cards/warrior/common/respite.tres
  resources/cards/warrior/common/scrape.tres
  resources/cards/warrior/gods_boon/ker.tres
  resources/cards/warrior/gods_boon/poseidon.tres
  resources/cards/warrior/gods_boon/zeus.tres
  resources/cards/warrior/hero/actaeon.tres
  resources/cards/warrior/hero/damokles.tres
  resources/cards/warrior/hero/nestor.tres
  resources/cards/warrior/hero/odysseus.tres
  resources/characters/warrior_cards.tres
Labels: refactoring
